---
title: "PCA"
format: html
editor: source
editor_options: 
  chunk_output_type: inline
---

```{r}

sorensen_s1 <- read_csv("../metadata/sorensen_table_s1.csv") |> 
  rename(sample_alias = `Seq-ID`)

sorensen_ena <- read_tsv('../metadata/PRJEB59576_Kuderna_2023.txt') |> 
  filter(str_detect(scientific_name, 'Papio') | str_detect(scientific_name, 'gelada')) |> 
  group_by(sample_alias, sample_accession) |> 
  summarise(
    n = n()) 

sorensen_total <- full_join(sorensen_s1, sorensen_ena, by = "sample_alias") |>
  rename(ind = sample_accession)

```


```{r}

library(tidyverse)

path = "../steps/15_run_pca/robinson_2019.filtered"

path = "../steps/15_run_pca/robinson_2019_and_kuderna_2023_NC_044995.1.filtered"

pca <- read_table(paste0(path, ".eigenvec"), col_names = FALSE)
eigenval <- scan(paste0(path, ".eigenval"))

# sort out the pca data
# remove nuisance column
pca <- pca[,-1]
# set names
names(pca)[1] <- "ind"
names(pca)[2:ncol(pca)] <- paste0("PC", 1:(ncol(pca)-1))

pca <- pca |> 
  full_join(sorensen_total, by = "ind")

```

```{r}

pve <- data.frame(PC = 1:length(eigenval), pve = eigenval/sum(eigenval)*100)
a <- ggplot(pve, aes(PC, pve)) + geom_bar(stat = "identity")
a + ylab("Percentage variance explained") + theme_light()

```

```{r fig.height=8, fig.width=10}

names <- pca |> 
  group_by(Genus, Species) |> 
  summarise(
    PC1 = max(PC1),
    PC2 = mean(PC2)
  ) |> 
  drop_na()

ggplot(pca) + 
  geom_point(aes(PC2, PC1, color = paste(Genus, Species)), shape = 21) + 
  geom_text(aes(PC2, PC1, color = paste(Genus, Species), label = paste(Genus, Species)), data = names) +
  theme_light() 

```

```{r fig.height=10, fig.width=14}

names <- pca |> 
  group_by(Origin) |> 
  summarise(
    PC1 = min(PC1),
    PC2 = mean(PC2)
  ) |> 
  drop_na()

ggplot(pca) + 
  geom_point(aes(PC2, PC1, color = Origin), shape = 21) + 
  geom_text(aes(PC2, PC1, color = Origin, label = Origin), data = names) +
  theme_light() 

```

```{r fig.height=10, fig.width=14}

names <- pca |> 
  filter(Species %in% c("anubis", "cynocephalus") | is.na(Species)) |> 
  group_by(Origin) |> 
  summarise(
    PC1 = min(PC1),
    PC2 = mean(PC2)
  ) |> 
  drop_na()

pca |> 
  filter(Species %in% c("anubis", "cynocephalus") | is.na(Species)) |> 
  ggplot() + 
  geom_point(aes(PC2, PC1, color = Origin), shape = 21) + 
  geom_text(aes(PC2, PC1, color = Origin, label = Origin), data = names) +
  theme_light() 

```



